version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=goodbiuser
      - DB_PASSWORD=goodbye
      - DB_NAME=goodbi-db
      - POSTGRES_URI=postgresql://goodbiuser:goodbye@db:5432/goodbi-db
      - SUPERTOKENS_CONNECTION_URI=https://st-dev-d077cc10-75bf-11ef-822f-59b1a0e8c720.aws.supertokens.io
      - SUPERTOKENS_API_KEY=FNvAao5-YkZKaRMPzgOhiVOek8
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/frontend
  #     - /frontend/node_modules
  #     - /frontend/.next
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #   depends_on:
  #     - backend

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=goodbiuser
      - POSTGRES_PASSWORD=goodbye
      - POSTGRES_DB=goodbi-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
