version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=goodbiuser
      - POSTGRES_PASSWORD=goodbye
      - POSTGRES_DB=goodbi-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
