# Use this sample metadata for testing so you don't use up your credits.
metadata = {
    'table_name': 'music_tracks',
    'column_names': [
        'track_name', 
        'artist(s)_name', 
        'artist_count', 
        'released_year', 
        'released_month', 
        'released_day', 
        'in_spotify_playlists', 
        'in_spotify_charts', 
        'streams', 
        'in_apple_playlists', 
        'in_apple_charts', 
        'in_deezer_playlists', 
        'in_deezer_charts', 
        'in_shazam_charts', 
        'bpm', 
        'key', 
        'mode', 
        'danceability_%', 
        'valence_%', 
        'energy_%', 
        'acousticness_%', 
        'instrumentalness_%', 
        'liveness_%', 
        'speechiness_%', 
        'cover_url'
    ],
    'column_descriptors': {
        'track_name': 'Name of the track',
        'artist(s)_name': 'Name(s) of the artist(s)',
        'artist_count': 'Number of artists',
        'released_year': 'Year of release',
        'released_month': 'Month of release',
        'released_day': 'Day of release',
        'in_spotify_playlists': 'Number of Spotify playlists the track is in',
        'in_spotify_charts': 'Number of Spotify charts the track is in',
        'streams': 'Number of streams',
        'in_apple_playlists': 'Number of Apple playlists the track is in',
        'in_apple_charts': 'Number of Apple charts the track is in',
        'in_deezer_playlists': 'Number of Deezer playlists the track is in',
        'in_deezer_charts': 'Number of Deezer charts the track is in',
        'in_shazam_charts': 'Number of Shazam charts the track is in',
        'bpm': 'Beats per minute',
        'key': 'Musical key of the track',
        'mode': 'Mode (Major/Minor)',
        'danceability_%': 'Danceability percentage',
        'valence_%': 'Valence percentage',
        'energy_%': 'Energy percentage',
        'acousticness_%': 'Acousticness percentage',
        'instrumentalness_%': 'Instrumentalness percentage',
        'liveness_%': 'Liveness percentage',
        'speechiness_%': 'Speechiness percentage',
        'cover_url': 'URL of the cover image'
    },
    'column_types': {
        'track_name': 'string',
        'artist(s)_name': 'string',
        'artist_count': 'integer',
        'released_year': 'integer',
        'released_month': 'integer',
        'released_day': 'integer',
        'in_spotify_playlists': 'integer',
        'in_spotify_charts': 'integer',
        'streams': 'string',
        'in_apple_playlists': 'integer',
        'in_apple_charts': 'integer',
        'in_deezer_playlists': 'string',
        'in_deezer_charts': 'integer',
        'in_shazam_charts': 'string',
        'bpm': 'integer',
        'key': 'string',
        'mode': 'string',
        'danceability_%': 'integer',
        'valence_%': 'integer',
        'energy_%': 'integer',
        'acousticness_%': 'integer',
        'instrumentalness_%': 'integer',
        'liveness_%': 'integer',
        'speechiness_%': 'integer',
        'cover_url': 'string'
    },
    'data_sample': [
        {
            'track_name': 'Seven (feat. Latto) (Explicit Ver.)',
            'artist(s)_name': 'Latto, Jung Kook',
            'artist_count': 2,
            'released_year': 2023,
            'released_month': 7,
            'released_day': 14,
            'in_spotify_playlists': 553,
            'in_spotify_charts': 147,
            'streams': '141381703',
            'in_apple_playlists': 43,
            'in_apple_charts': 263,
            'in_deezer_playlists': '45',
            'in_deezer_charts': 10,
            'in_shazam_charts': '826',
            'bpm': 125,
            'key': 'B',
            'mode': 'Major',
            'danceability_%': 80,
            'valence_%': 89,
            'energy_%': 83,
            'acousticness_%': 31,
            'instrumentalness_%': 0,
            'liveness_%': 8,
            'speechiness_%': 4,
            'cover_url': 'Not Found'
        },
        {
            'track_name': 'LALA',
            'artist(s)_name': 'Myke Towers',
            'artist_count': 1,
            'released_year': 2023,
            'released_month': 3,
            'released_day': 23,
            'in_spotify_playlists': 1474,
            'in_spotify_charts': 48,
            'streams': '133716286',
            'in_apple_playlists': 48,
            'in_apple_charts': 126,
            'in_deezer_playlists': '58',
            'in_deezer_charts': 14,
            'in_shazam_charts': '382',
            'bpm': 92,
            'key': 'C#',
            'mode': 'Major',
            'danceability_%': 71,
            'valence_%': 61,
            'energy_%': 74,
            'acousticness_%': 7,
            'instrumentalness_%': 0,
            'liveness_%': 10,
            'speechiness_%': 4,
            'cover_url': 'https://i.scdn.co/image/ab67616d0000b2730656d5ce813ca3cc4b677e05'
        },
        {
            'track_name': 'vampire',
            'artist(s)_name': 'Olivia Rodrigo',
            'artist_count': 1,
            'released_year': 2023,
            'released_month': 6,
            'released_day': 30,
            'in_spotify_playlists': 1397,
            'in_spotify_charts': 113,
            'streams': '140003974',
            'in_apple_playlists': 94,
            'in_apple_charts': 207,
            'in_deezer_playlists': '91',
            'in_deezer_charts': 14,
            'in_shazam_charts': '949',
            'bpm': 138,
            'key': 'F',
            'mode': 'Major',
            'danceability_%': 51,
            'valence_%': 32,
            'energy_%': 53,
            'acousticness_%': 17,
            'instrumentalness_%': 0,
            'liveness_%': 31,
            'speechiness_%': 6,
            'cover_url': 'https://i.scdn.co/image/ab67616d0000b273e85259a1cae29a8d91f2093d'
        }
    ],
    'noun_columns': ['track_name', 'artist(s)_name', 'cover_url']
}